### ISSUE TITLE
pod install fails on react native 0.61.5

### ISSUE THREAD

**Issue by HannanShaikYara** [instana/react-native-agent#2]
Hi Team,

I just installed this package via 

`yarn add @instana/react-native-agent` (`v.1.0.1`)

When try to do `pod install` I get the below error. Please help.

```
!] CocoaPods could not find compatible versions for pod "instana_react-native-agent":
  In Podfile:
    instana_react-native-agent (from `../node_modules/@instana/react-native-agent`)

Specs satisfying the `instana_react-native-agent (from `../node_modules/@instana/react-native-agent`)` dependency were found, but they required a higher minimum deployment target.


```

**Comment by tapwork** [comment]
Hi ! Which deployment target did you specify in your setup? We require to have at least iOS 11.0

**Comment by HannanShaikYara** [comment]
Oh. Unfortunately I support ios 9 onwards. Is there any plan to support that?

**Comment by tapwork** [comment]
Sorry. no plans yet to support older versions since only 0.5-1% of the iOS users still run iOS 9 or 10
